# configure your datasource
quarkus.datasource.db-kind = mysql # tipo de banco a ser usado
quarkus.datasource.username = root # usuario do banco a ser usado
quarkus.datasource.password = # Senha vazia no nosso caso
quarkus.datasource.jdbc.url = jdbc:mysql://localhost:3306/projeto #link de coneção do banco

# drop and create the database at startup (use `update` to only update the schema)
quarkus.hibernate-orm.schema-management.strategy = drop-and-create